use_frameworks!

target 'Example' do
  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', :git => 'https://github.com/popstand/Charts.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
